#include "img2dat.h"

#include <QPainter>
#include <QTextStream>
#include <QCoreApplication>

Img2Dat::Img2Dat()
{
    setTransparentColor(QColor(255, 0, 255));
}

int Img2Dat::ceilingMultiple(int x, int multiple)
{
    if (x % multiple == 0)
        return x;
    else
        return ((x / multiple) + 1) * multiple;
}

void Img2Dat::setTransparentColor(QColor color)
{
    transparent = color;
}

QString Img2Dat::convert(QImage image,
        QString filename,
        int framewidth,
        int frameheight,
        int range)
{
    // chop into frames
    int framecountx = image.width() / framewidth;
    if (image.width() % framewidth > 0)
        framecountx++;
    int framecounty = image.height() / frameheight;
    if (image.height() % frameheight > 0)
        framecounty++;

    int newframewidth  = ceilingMultiple(framewidth, 8);
    int newframeheight = frameheight;
    int newwidth  = ceilingMultiple(image.width()  * newframewidth  / framewidth,8);
    int newheight = ceilingMultiple(image.height() * newframeheight / frameheight, newframeheight);

    //    qDebug() << "   Frame Count: (" << framecountx << "," << framecounty << ")";
    //    qDebug() << "Old Frame Size: (" << framewidth << "," << frameheight << ")";
    //    qDebug() << "New Frame Size: (" << newframewidth << "," << newframeheight << ")";
    //    qDebug() << "New Image Size: (" << newwidth << "," << newheight << ")";

    QImage newimage(newwidth, newheight, QImage::Format_RGB32);
    newimage.fill(transparent);

    QPainter paint(&newimage);

    for (int fy = 0; fy < framecounty; fy++)
    {
        for (int fx = 0; fx < framecountx; fx++)
        {
            paint.drawImage(fx*newframewidth,   fy*newframeheight,
                    image,
                    fx*framewidth,      fy*frameheight,
                    framewidth,         frameheight);
        }
    }

    // detect dynamic range
    int low, high;
    low = high = QColor(image.pixel(0, 0)).lightness();

    for (int y = 0; y < image.height(); y++)
    {
        for (int x = 0; x < image.width(); x++)
        {
            QColor color(image.pixel(x, y));
            if (color != transparent)
            {
                int lightness = color.lightness();
                low = qMin(low, lightness);
                high = qMax(high, lightness);
            }
        }
    }


    // calculate range breakpoints
    int mid = (low + high) / 2;
    int lowbreak = mid - (mid - low) * range / 100;
    int highbreak = mid + (high - mid) * range / 100;

    //    qDebug() << " Dynamic Range: ( L" << low << ", M" << mid << ", H" << high << ")";
    //    qDebug() << "        Breaks: (" << lowbreak << "," << highbreak << ")" << range << "%";



    // generate data structure
    int ** newimagedata = new int*[newimage.height()];


    for (int y = 0; y < newimage.height(); y++)
    {
        newimagedata[y] = new int[newimage.width()];

        for (int x = 0; x < newimage.width(); x++)
        {
            QColor color = newimage.pixel(x, y);
            int lightness = color.lightness();
            if (color == transparent)
            {
                newimagedata[y][x] = 2;
            }
            else
            {
                if (lightness >= highbreak)
                    newimagedata[y][x] = 1;
                else if (lightness <= lowbreak)
                    newimagedata[y][x] = 0;
                else
                    newimagedata[y][x] = 3;
            }
        }
    }

    // calculate frameboost
    
    int frameboost = framewidth * frameheight * 2 / 8;

    QString output;
    QTextStream stream(&output);

    stream  << "' *********************************************************\n"
        << "' " << filename << "\n"
        << "' generated by img2dat " << qApp->applicationVersion() << "\n"
        << "' *********************************************************\n"
        << "PUB Addr\n"
        << "    return @data\n\n"
        << "DAT\n\n"
        << "data\n"
        << "word    " << frameboost << "\n"
        << "word    " << framewidth << ", " << frameheight << "\n";

    // print data
    unsigned short word = 0;
    for (int fy = 0; fy < framecounty; fy++)
    {
        for (int fx = 0; fx < framecountx; fx++)
        {
            for (int y = 0; y < newframeheight; y++)
            {
                stream << "word    ";
                word = 0;
                for (int x = 0; x < newframewidth; x++)
                {
                    if (x % 8 == 0)
                    {
                        word = 0;
                    }
                    word += (newimagedata[fy*newframeheight+y][fx*newframewidth+x] << ((x % 8)*2));

                    if (x % 8 == 7)
                    {
                        stream << QString("$%1").arg(word,4,16,QChar('0'));
                        if (x < newframewidth-1)
                            stream << ",";
                    }

                }

                stream << " ' ";
                for (int x = 0; x < newframewidth; x++)
                {
                    QString s;
                    switch (newimagedata[fy*newframeheight+y][fx*newframewidth+x])
                    {
                        case 2: s = " ";
                                break;
                        case 1: s = "░";
                                break;
                        case 3: s = "▓";
                                break;
                        case 0: s = "█";
                                break;
                    }
                    stream << s;
                }

                stream << "\n";
            }
            stream << "\n";
        }
    }

    return output;
}
